apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hiring-router-mcp
  annotations:
    run.googleapis.com/ingress: all
    autoscaling.knative.dev/minScale: "1"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: "hiring-router-mcp"
        run.googleapis.com/timeout: "3600s"
    spec:
      containerConcurrency: 80
      containers:
        - image: europe-west1-docker.pkg.dev/qalearn/hiring-router/hiring-router-mcp:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"

